"use client";

import { useMemo, useState } from "react";
import {
  useServiceTemplates,
  useServiceOverrides,
  useReservationSettings,
  createServiceTemplate,
  updateServiceTemplate,
  deleteServiceTemplate,
  upsertServiceOverride,
  deleteServiceOverride,
  deleteServiceOverridesForDate,
  updateReservationSettings,
} from "@/lib/data";
import { servicesForDate, servicesOverlap, toMin } from "@/lib/reservation/services";

const inputStyle = { background: "#211712", border: "1px solid #3a2b1f", color: "#f5ebdd" };
const todayISO = () => new Date().toISOString().slice(0, 10);

function TimeInput({ value, onCommit }) {
  return (
    <input
      type="time"
      defaultValue={value}
      key={value}
      onBlur={(e) => e.target.value && e.target.value !== value && onCommit(e.target.value)}
      className="rounded-lg px-2 py-1 text-sm"
      style={inputStyle}
    />
  );
}
function NumInput({ value, min = 0, onCommit }) {
  return (
    <input
      type="number"
      min={min}
      defaultValue={value ?? ""}
      key={String(value)}
      onBlur={(e) => {
        const v = e.target.value === "" ? null : Math.max(min, parseInt(e.target.value, 10) || 0);
        if (v !== value) onCommit(v);
      }}
      className="w-16 rounded-lg px-2 py-1 text-sm"
      style={inputStyle}
    />
  );
}

export default function ServicesAdmin() {
  const { serviceTemplates } = useServiceTemplates();
  const { serviceOverrides } = useServiceOverrides();
  const { settings } = useReservationSettings();
  const [date, setDate] = useState(todayISO());

  const resolved = useMemo(
    () => servicesForDate(date, serviceTemplates, serviceOverrides),
    [date, serviceTemplates, serviceOverrides]
  );
  const overlap = servicesOverlap(resolved);
  const dateOverrides = serviceOverrides.filter((o) => o.date === date);

  // Affichage chronologique : le numéro de service reste l'identité, mais on
  // liste les services par heure de début (un service ajouté plus tard peut
  // commencer plus tôt).
  const sortedTemplates = useMemo(
    () =>
      [...serviceTemplates].sort(
        (a, b) => (toMin(a.startTime) ?? 0) - (toMin(b.startTime) ?? 0) || a.serviceNumber - b.serviceNumber
      ),
    [serviceTemplates]
  );

  function addTemplate() {
    const nextNum = (serviceTemplates.reduce((m, t) => Math.max(m, t.serviceNumber), 0) || 0) + 1;
    const last = sortedTemplates[sortedTemplates.length - 1];
    const start = last?.endTime || "19:00";
    createServiceTemplate({
      serviceNumber: nextNum,
      label: `${nextNum}${nextNum === 1 ? "er" : "e"} service`,
      startTime: start,
      endTime: "22:30",
      maxCovers: 40,
      activeByDefault: nextNum === 1,
    }).catch((e) => console.error(e));
  }

  // Bascule/édite un service pour la date choisie → écrit un override.
  function overrideService(s, patch) {
    upsertServiceOverride({
      date,
      serviceNumber: s.serviceNumber,
      startTime: patch.startTime ?? s.startTime,
      endTime: patch.endTime ?? s.endTime,
      maxCovers: patch.maxCovers !== undefined ? patch.maxCovers : s.maxCovers,
      isActive: patch.isActive !== undefined ? patch.isActive : true,
      autoGenerated: s.autoGenerated || false,
    }).catch((e) => console.error(e));
  }
  // Réactiver pour cette date un service désactivé par défaut.
  function activateTemplateForDate(tpl) {
    upsertServiceOverride({
      date,
      serviceNumber: tpl.serviceNumber,
      startTime: tpl.startTime,
      endTime: tpl.endTime,
      maxCovers: tpl.maxCovers,
      isActive: true,
    }).catch((e) => console.error(e));
  }

  const inactiveTemplatesForDate = sortedTemplates.filter(
    (t) => !resolved.some((r) => r.serviceNumber === t.serviceNumber) && !dateOverrides.some((o) => o.serviceNumber === t.serviceNumber)
  );

  return (
    <div className="flex-1 overflow-y-auto px-6 py-4">
      <div className="text-xs text-[#8a7561] mb-5 max-w-2xl">
        Les <b>services par défaut</b> (1er, 2e…) s'appliquent chaque jour selon leur drapeau « actif par défaut ».
        Les <b>ajustements par date</b> activent / désactivent ou décalent un service pour une date précise. Un service
        <b> auto-généré</b> apparaît quand une réservation tombe hors des services actifs (Phase 7).
      </div>

      {/* --- Services par défaut --- */}
      <div className="rounded-xl border border-[#3a2b1f] bg-[#211712] p-4 mb-4">
        <div className="text-xs text-[#a88f78] uppercase font-bold mb-3">Services par défaut</div>
        <div className="flex flex-col gap-2">
          {sortedTemplates.map((t) => (
            <div key={t.id} className="flex flex-wrap items-center gap-2 text-sm">
              <span className="text-xs text-[#8a7561] w-5">#{t.serviceNumber}</span>
              <input
                defaultValue={t.label || ""}
                key={t.label}
                onBlur={(e) => e.target.value !== (t.label || "") && updateServiceTemplate(t.id, { label: e.target.value }).catch((err) => console.error(err))}
                placeholder="Nom"
                className="rounded-lg px-2 py-1 text-sm w-40"
                style={inputStyle}
              />
              <TimeInput value={t.startTime} onCommit={(v) => updateServiceTemplate(t.id, { startTime: v }).catch((e) => console.error(e))} />
              <span className="text-[#8a7561]">→</span>
              <TimeInput value={t.endTime} onCommit={(v) => updateServiceTemplate(t.id, { endTime: v }).catch((e) => console.error(e))} />
              <label className="flex items-center gap-1 text-xs text-[#a88f78]">
                couv. max
                <NumInput value={t.maxCovers} min={1} onCommit={(v) => updateServiceTemplate(t.id, { maxCovers: v }).catch((e) => console.error(e))} />
              </label>
              <button
                onClick={() => updateServiceTemplate(t.id, { activeByDefault: !t.activeByDefault }).catch((e) => console.error(e))}
                className="tap-scale rounded-full px-3 py-1 text-xs font-bold border-2"
                style={t.activeByDefault ? { borderColor: "#204a3a", color: "#a8e8c8" } : { borderColor: "#4a3a10", color: "#e8b23d" }}
              >
                {t.activeByDefault ? "actif par défaut" : "inactif par défaut"}
              </button>
              <button onClick={() => deleteServiceTemplate(t.id).catch((e) => console.error(e))} className="tap-scale text-xs text-red-400 font-bold">
                ✕
              </button>
            </div>
          ))}
          {serviceTemplates.length === 0 && <span className="text-xs text-[#5a4a3a]">Aucun service défini.</span>}
        </div>
        <button onClick={addTemplate} className="tap-scale mt-3 rounded-full px-3 py-1.5 text-xs font-bold border-2 border-[#3a2b1f]">
          + Ajouter un service
        </button>
      </div>

      {/* --- Réglages --- */}
      <div className="rounded-xl border border-[#3a2b1f] bg-[#211712] p-4 mb-4">
        <div className="text-xs text-[#a88f78] uppercase font-bold mb-3">Réglages réservation</div>
        <div className="flex flex-wrap items-center gap-4 text-sm">
          <label className="flex items-center gap-2 text-xs text-[#a88f78]">
            Délai minimum avant réservation (min)
            <NumInput value={settings.bookingLeadMinutes} min={0} onCommit={(v) => updateReservationSettings({ bookingLeadMinutes: v ?? 30 }).catch((e) => console.error(e))} />
          </label>
          <label className="flex items-center gap-2 text-xs text-[#a88f78]">
            Marge de sécurité (min)
            <NumInput value={settings.safetyMarginMinutes} min={0} onCommit={(v) => updateReservationSettings({ safetyMarginMinutes: v ?? 0 }).catch((e) => console.error(e))} />
          </label>
          <label className="flex items-center gap-2 text-xs text-[#a88f78]">
            Pas des créneaux (min)
            <NumInput value={settings.slotGranularityMinutes} min={5} onCommit={(v) => updateReservationSettings({ slotGranularityMinutes: v ?? 15 }).catch((e) => console.error(e))} />
          </label>
          <button
            onClick={() => updateReservationSettings({ onlineBookingEnabled: !settings.onlineBookingEnabled }).catch((e) => console.error(e))}
            className="tap-scale rounded-full px-3 py-1.5 text-xs font-bold border-2"
            style={settings.onlineBookingEnabled ? { borderColor: "#204a3a", color: "#a8e8c8" } : { borderColor: "#3a2b1f", color: "#c9b8a4" }}
          >
            {settings.onlineBookingEnabled ? "✓ Réservation en ligne activée" : "Réservation en ligne désactivée"}
          </button>
        </div>

        <div className="mt-4 pt-3 border-t border-[#3a2b1f]">
          <div className="flex flex-wrap items-center gap-3 text-xs text-[#a88f78]">
            Plage des services auto-générés — de
            <TimeInput value={settings.earliestServiceTime} onCommit={(v) => updateReservationSettings({ earliestServiceTime: v }).catch((e) => console.error(e))} />
            à
            <TimeInput value={settings.latestServiceTime} onCommit={(v) => updateReservationSettings({ latestServiceTime: v }).catch((e) => console.error(e))} />
          </div>
          <div className="text-xs text-[#5a4a3a] mt-1 max-w-2xl">
            Bornes utilisées uniquement quand une réservation tombe hors de tous les services actifs et qu'un service
            est créé automatiquement pour l'accueillir. N'a aucun effet sur les créneaux proposés en ligne, qui
            dépendent seulement des services actifs du jour et du pas des créneaux.
          </div>
        </div>
      </div>

      {/* --- Ajustements par date --- */}
      <div className="rounded-xl border border-[#3a2b1f] bg-[#211712] p-4">
        <div className="flex items-center gap-3 mb-3">
          <span className="text-xs text-[#a88f78] uppercase font-bold">Ajustements pour le</span>
          <input type="date" value={date} onChange={(e) => setDate(e.target.value)} className="rounded-lg px-2 py-1 text-sm" style={inputStyle} />
          {dateOverrides.length > 0 && (
            <button onClick={() => deleteServiceOverridesForDate(date).catch((e) => console.error(e))} className="tap-scale text-xs text-red-400 font-bold">
              Réinitialiser cette date
            </button>
          )}
        </div>

        {overlap && (
          <div className="text-xs mb-2" style={{ color: "#e8b23d" }}>
            ⚠️ Des services se chevauchent pour cette date.
          </div>
        )}

        <div className="flex flex-col gap-2">
          {resolved.map((s) => (
            <div key={s.serviceNumber} className="flex flex-wrap items-center gap-2 text-sm">
              <span className="font-bold">{s.label}</span>
              {s.autoGenerated && (
                <span className="text-xs rounded-full px-2 py-0.5" style={{ background: "#4a3a10", color: "#e8b23d" }}>
                  auto
                </span>
              )}
              {s.hasOverride && !s.autoGenerated && <span className="text-xs text-[#8a7561]">(ajusté)</span>}
              <TimeInput value={s.startTime} onCommit={(v) => overrideService(s, { startTime: v })} />
              <span className="text-[#8a7561]">→</span>
              <TimeInput value={s.endTime} onCommit={(v) => overrideService(s, { endTime: v })} />
              <label className="flex items-center gap-1 text-xs text-[#a88f78]">
                couv. max
                <NumInput value={s.maxCovers} min={1} onCommit={(v) => overrideService(s, { maxCovers: v })} />
              </label>
              <button
                onClick={() => overrideService(s, { isActive: false })}
                className="tap-scale rounded-full px-3 py-1 text-xs font-bold border-2 border-[#4a2020] text-[#e8a8a8]"
              >
                Désactiver ce jour
              </button>
            </div>
          ))}
          {resolved.length === 0 && <span className="text-xs text-[#5a4a3a]">Aucun service actif ce jour-là.</span>}
        </div>

        {inactiveTemplatesForDate.length > 0 && (
          <div className="mt-3 flex flex-wrap gap-2">
            {inactiveTemplatesForDate.map((t) => (
              <button
                key={t.id}
                onClick={() => activateTemplateForDate(t)}
                className="tap-scale rounded-full px-3 py-1.5 text-xs font-bold border-2 border-[#204a3a] text-[#a8e8c8]"
              >
                + Activer « {t.label || `Service ${t.serviceNumber}`} » ce jour
              </button>
            ))}
          </div>
        )}

        {/* réactiver un service désactivé ponctuellement (override isActive=false) */}
        {dateOverrides.filter((o) => !o.isActive).map((o) => {
          const tpl = serviceTemplates.find((t) => t.serviceNumber === o.serviceNumber);
          return (
            <button
              key={o.id}
              onClick={() => upsertServiceOverride({ date, serviceNumber: o.serviceNumber, startTime: o.startTime, endTime: o.endTime, maxCovers: o.maxCovers, isActive: true }).catch((e) => console.error(e))}
              className="tap-scale mt-2 rounded-full px-3 py-1.5 text-xs font-bold border-2 border-[#204a3a] text-[#a8e8c8]"
            >
              Réactiver « {tpl?.label || `Service ${o.serviceNumber}`} » ce jour
            </button>
          );
        })}
      </div>
    </div>
  );
}
