// Tests des services de réservation. Lancer : node lib/reservation/services.test.mjs
import { toMin, toHHMM, weekdayOf, servicesForDate, serviceForTime, servicesOverlap, planAutoExtension, autoZoneCovers, applyAutoZoneCovers } from "./services.js";

let passed = 0;
let failed = 0;
function ok(cond, name) {
  if (cond) passed++;
  else {
    failed++;
    console.error("  ✗ " + name);
  }
}

// --- helpers heure ---
ok(toMin("19:30") === 1170, "toMin 19:30");
ok(toMin("19:30:00") === 1170, "toMin gère le suffixe :00");
ok(toHHMM(1170) === "19:30", "toHHMM 1170");
ok(toHHMM(toMin("22:05")) === "22:05", "roundtrip");

// --- servicesForDate ---
const templates = [
  { serviceNumber: 1, label: "1er service", startTime: "19:00", endTime: "20:30", maxCovers: 40, activeByDefault: true },
  { serviceNumber: 2, label: "2e service", startTime: "20:30", endTime: "22:30", maxCovers: 40, activeByDefault: false },
];
{
  const s = servicesForDate("2026-09-10", templates, []);
  ok(s.length === 1 && s[0].serviceNumber === 1, "template active_by_default → seul le 1er service");
}
{
  // override qui active le 2e service ce jour-là
  const ov = [{ date: "2026-09-10", serviceNumber: 2, startTime: "20:30", endTime: "22:30", maxCovers: 40, isActive: true, autoGenerated: false }];
  const s = servicesForDate("2026-09-10", templates, ov);
  ok(s.length === 2, "override isActive → 2e service ajouté");
  ok(servicesForDate("2026-09-11", templates, ov).length === 1, "override ne vaut que pour sa date");
}
{
  // override qui désactive le 1er service
  const ov = [{ date: "2026-09-10", serviceNumber: 1, startTime: "19:00", endTime: "20:30", isActive: false, autoGenerated: false }];
  ok(servicesForDate("2026-09-10", templates, ov).length === 0, "override isActive=false → 1er service retiré");
}
{
  // override qui change les horaires
  const ov = [{ date: "2026-09-10", serviceNumber: 1, startTime: "18:30", endTime: "20:00", maxCovers: 30, isActive: true, autoGenerated: false }];
  const s = servicesForDate("2026-09-10", templates, ov);
  ok(s[0].startTime === "18:30" && s[0].maxCovers === 30 && s[0].hasOverride, "override horaires prioritaire");
}

// --- activation par jour de semaine ---
ok(weekdayOf("2026-09-12") === 6 && weekdayOf("2026-09-09") === 3, "weekdayOf : samedi=6, mercredi=3");
{
  // 2e service actif seulement ven/sam/dim
  const t = [
    { serviceNumber: 1, label: "1er", startTime: "12:00", endTime: "14:30", activeWeekdays: [1, 2, 3, 4, 5, 6, 0] },
    { serviceNumber: 2, label: "2e", startTime: "19:00", endTime: "22:30", activeWeekdays: [5, 6, 0] },
  ];
  ok(servicesForDate("2026-09-12", t, []).length === 2, "samedi → 1er + 2e service");
  ok(servicesForDate("2026-09-09", t, []).length === 1, "mercredi → 1er service seulement");
  // un ajustement de date prime sur le jour de semaine « off »
  const ov = [{ date: "2026-09-09", serviceNumber: 2, startTime: "19:00", endTime: "22:30", isActive: true, autoGenerated: false }];
  ok(servicesForDate("2026-09-09", t, ov).length === 2, "override isActive prime sur le jour de semaine off");
}
{
  // repli : template sans activeWeekdays → activeByDefault
  const t = [{ serviceNumber: 1, label: "1er", startTime: "12:00", endTime: "14:30", activeByDefault: true }];
  ok(servicesForDate("2026-09-09", t, []).length === 1, "sans activeWeekdays → repli sur activeByDefault");
}

// --- couverts max par zone (maxCoversByLayout) ---
{
  const t = [{ serviceNumber: 1, label: "Midi", startTime: "12:00", endTime: "14:30", activeByDefault: true, maxCovers: 50, maxCoversByLayout: { salle: 30, terrasse: 20 } }];
  const s = servicesForDate("2026-09-10", t, [])[0];
  ok(s.maxCoversByLayout.salle === 30 && s.maxCoversByLayout.terrasse === 20, "service résolu porte maxCoversByLayout");
  ok(s.maxCovers === 50, "maxCovers (total) inchangé");

  // override avec découpage → prime
  const ov = [{ date: "2026-09-10", serviceNumber: 1, startTime: "12:00", endTime: "14:30", isActive: true, autoGenerated: false, maxCovers: 40, maxCoversByLayout: { salle: 25, terrasse: 15 } }];
  ok(servicesForDate("2026-09-10", t, ov)[0].maxCoversByLayout.salle === 25, "override maxCoversByLayout non vide prime");

  // override sans découpage ({}) → on garde celui du template
  const ov2 = [{ date: "2026-09-10", serviceNumber: 1, startTime: "12:00", endTime: "14:30", isActive: true, autoGenerated: false, maxCovers: 40, maxCoversByLayout: {} }];
  ok(servicesForDate("2026-09-10", t, ov2)[0].maxCoversByLayout.salle === 30, "override {} → repli sur le découpage du template");
}

// --- exceptions : planning annuel des fermetures ---
const wt = [
  { serviceNumber: 1, label: "Midi", startTime: "12:00", endTime: "14:30", activeWeekdays: [0, 1, 2, 3, 4, 5, 6] },
  { serviceNumber: 2, label: "Soir", startTime: "19:00", endTime: "22:30", activeWeekdays: [0, 1, 2, 3, 4, 5, 6] },
];
{
  const exc = [{ dateStart: "2026-10-05", dateEnd: "2026-10-11", serviceNumber: null, mode: "off", label: "Congés" }];
  ok(servicesForDate("2026-10-07", wt, [], exc).length === 0, "congés (global off) → aucun service dans la plage");
  ok(servicesForDate("2026-10-15", wt, [], exc).length === 2, "hors plage → services normaux");
}
{
  const exc = [{ dateStart: "2026-10-05", dateEnd: "2026-10-11", serviceNumber: 2, mode: "off" }];
  const s = servicesForDate("2026-10-07", wt, [], exc);
  ok(s.length === 1 && s[0].serviceNumber === 1, "coupure d'un service précis sur une plage");
}
{
  // service normalement off le mercredi, forcé actif sur une plage
  const t = [{ serviceNumber: 2, label: "Soir", startTime: "19:00", endTime: "22:30", activeWeekdays: [5, 6, 0] }];
  const exc = [{ dateStart: "2026-10-05", dateEnd: "2026-10-11", serviceNumber: 2, mode: "on" }];
  ok(servicesForDate("2026-10-07", t, [], exc).length === 1, "exception 'on' force un service normalement inactif");
}
{
  const exc = [
    { dateStart: "2026-10-05", dateEnd: "2026-10-11", serviceNumber: null, mode: "off", label: "Congés" },
    { dateStart: "2026-10-07", dateEnd: "2026-10-07", serviceNumber: null, mode: "on", label: "Ouvert" },
  ];
  ok(servicesForDate("2026-10-07", wt, [], exc).length === 2, "ouverture except. (plage plus courte) prime sur la fermeture");
  ok(servicesForDate("2026-10-08", wt, [], exc).length === 0, "les autres jours de la plage restent fermés");
}
{
  // service_overrides exact prime sur une exception qui recouvre la date
  const exc = [{ dateStart: "2026-10-05", dateEnd: "2026-10-11", serviceNumber: null, mode: "off" }];
  const ov = [{ date: "2026-10-07", serviceNumber: 1, startTime: "12:00", endTime: "14:30", isActive: true, autoGenerated: false }];
  const s = servicesForDate("2026-10-07", wt, ov, exc);
  ok(s.length === 1 && s[0].serviceNumber === 1, "service_overrides exact prime sur l'exception");
}

// --- serviceForTime ---
{
  const s = servicesForDate("2026-09-10", templates, [
    { date: "2026-09-10", serviceNumber: 2, startTime: "20:30", endTime: "22:30", isActive: true, autoGenerated: false },
  ]);
  ok(serviceForTime(s, "19:15")?.serviceNumber === 1, "19:15 → 1er service");
  ok(serviceForTime(s, "20:30")?.serviceNumber === 2, "20:30 → 2e service (fin exclusive du 1er)");
  ok(serviceForTime(s, "23:00") === null, "23:00 → aucun service");
  ok(serviceForTime(s, "12:00") === null, "12:00 → aucun service");
}

// --- servicesOverlap ---
ok(servicesOverlap([{ startMin: 1140, endMin: 1230 }, { startMin: 1200, endMin: 1350 }]) === true, "chevauchement détecté");
ok(servicesOverlap([{ startMin: 1140, endMin: 1230 }, { startMin: 1230, endMin: 1350 }]) === false, "adjacents = pas de chevauchement");

// --- planAutoExtension ---
const settings = { earliestServiceTime: "18:00", latestServiceTime: "22:30", slotGranularityMinutes: 15 };
{
  const active = servicesForDate("2026-09-10", templates, []); // seul 1er service 19:00-20:30
  let r = planAutoExtension(active, "18:15", settings);
  ok(r.ok && r.service.startTime === "18:15" && toMin(r.service.endTime) <= toMin("19:00"), "18:15 → service auto 18:15→≤19:00");

  r = planAutoExtension(active, "17:30", settings);
  ok(!r.ok && r.reason === "hors-plage", "17:30 < earliest → refus hors-plage");

  r = planAutoExtension(active, "19:30", settings);
  ok(!r.ok && r.reason === "deja-couvert", "19:30 déjà dans le 1er service → refus");

  r = planAutoExtension(active, "22:00", settings);
  ok(!r.ok, "22:00 : de 20:30 à 22:30 il reste 120 min mais start arrondi… vérifie juste refus/ok cohérent");
}
{
  // 1er service jusqu'à 20:30, latest 22:30 → une résa à 21:00 tient (21:00→22:30)
  const active = servicesForDate("2026-09-10", templates, []);
  const r = planAutoExtension(active, "21:00", settings);
  ok(r.ok && r.service.startTime === "21:00" && r.service.endTime === "22:30", "21:00 après le 1er service → 21:00→22:30");
  ok(r.service.serviceNumber >= 90, "service auto numéroté ≥ 90");
}
{
  // fenêtre trop courte : latest 20:45, résa à 20:30 juste après le 1er service
  const r = planAutoExtension(servicesForDate("2026-09-10", templates, []), "20:30", { ...settings, latestServiceTime: "20:45" });
  ok(!r.ok && r.reason === "creneau-trop-court", "fenêtre < 45 min → refus creneau-trop-court");
}

// --- autoZoneCovers / applyAutoZoneCovers ---
const T = (id, layoutId, cap, opts = {}) => ({
  id, layoutId, capacityMax: cap, active: true, blocked: false, gridRow: 0, gridCol: 0, ...opts,
});
const L = (id, name) => ({ id, name });
{
  const layouts = [L("salle", "Salle"), L("terrasse", "Terrasse")];
  const tables = [
    T("t1", "salle", 4),
    T("t2", "salle", 6),
    T("t3", "terrasse", 4),
    T("t4", "terrasse", 4),
    T("t5", "terrasse", 8, { blocked: true }), // bloquée → hors capacité
    T("t6", "terrasse", 8, { active: false }), // inactive → hors capacité
    T("t7", "terrasse", 8, { gridRow: null }), // pas placée → hors capacité
    T("t8", null, 4), // aucune zone → ignorée
  ];
  const auto = autoZoneCovers(tables, layouts);
  ok(auto.salle === 10 && auto.terrasse === 8, "capacité = somme des tables actives/placées/non bloquées de la zone");

  const services = [
    { serviceNumber: 1, maxCovers: null, maxCoversByLayout: {} }, // tout auto
    { serviceNumber: 2, maxCovers: null, maxCoversByLayout: { salle: 20 } }, // salle forcée, terrasse auto
  ];
  const applied = applyAutoZoneCovers(services, tables, layouts);
  ok(applied[0].maxCoversByLayout.salle === 10 && applied[0].maxCoversByLayout.terrasse === 8, "service sans saisie → tout auto");
  ok(applied[0].maxCovers === 18, "maxCovers = somme des zones (auto)");
  ok(applied[1].maxCoversByLayout.salle === 20 && applied[1].maxCoversByLayout.terrasse === 8, "zone saisie gardée, l'autre reste auto");
  ok(applied[1].maxCovers === 28, "maxCovers recalculé = somme (20 forcé + 8 auto)");
}
{
  // une seule zone (ou aucune) → pas de découpage, maxCovers = capacité totale
  const layouts = [L("salle", "Salle")];
  const tables = [T("t1", "salle", 4), T("t2", "salle", 4)];
  const applied = applyAutoZoneCovers([{ serviceNumber: 1, maxCovers: null }], tables, layouts);
  ok(applied[0].maxCovers === 8, "1 seule zone, rien saisi → auto = capacité totale");
  const applied2 = applyAutoZoneCovers([{ serviceNumber: 1, maxCovers: 25 }], tables, layouts);
  ok(applied2[0].maxCovers === 25, "1 seule zone, valeur saisie → conservée telle quelle");
}

console.log(`\nservices: ${passed} passed, ${failed} failed`);
process.exit(failed ? 1 : 0);
