// Tests des services de réservation. Lancer : node lib/reservation/services.test.mjs
import { toMin, toHHMM, servicesForDate, serviceForTime, servicesOverlap, planAutoExtension } from "./services.js";

let passed = 0;
let failed = 0;
function ok(cond, name) {
  if (cond) passed++;
  else {
    failed++;
    console.error("  ✗ " + name);
  }
}

// --- helpers heure ---
ok(toMin("19:30") === 1170, "toMin 19:30");
ok(toMin("19:30:00") === 1170, "toMin gère le suffixe :00");
ok(toHHMM(1170) === "19:30", "toHHMM 1170");
ok(toHHMM(toMin("22:05")) === "22:05", "roundtrip");

// --- servicesForDate ---
const templates = [
  { serviceNumber: 1, label: "1er service", startTime: "19:00", endTime: "20:30", maxCovers: 40, activeByDefault: true },
  { serviceNumber: 2, label: "2e service", startTime: "20:30", endTime: "22:30", maxCovers: 40, activeByDefault: false },
];
{
  const s = servicesForDate("2026-09-10", templates, []);
  ok(s.length === 1 && s[0].serviceNumber === 1, "template active_by_default → seul le 1er service");
}
{
  // override qui active le 2e service ce jour-là
  const ov = [{ date: "2026-09-10", serviceNumber: 2, startTime: "20:30", endTime: "22:30", maxCovers: 40, isActive: true, autoGenerated: false }];
  const s = servicesForDate("2026-09-10", templates, ov);
  ok(s.length === 2, "override isActive → 2e service ajouté");
  ok(servicesForDate("2026-09-11", templates, ov).length === 1, "override ne vaut que pour sa date");
}
{
  // override qui désactive le 1er service
  const ov = [{ date: "2026-09-10", serviceNumber: 1, startTime: "19:00", endTime: "20:30", isActive: false, autoGenerated: false }];
  ok(servicesForDate("2026-09-10", templates, ov).length === 0, "override isActive=false → 1er service retiré");
}
{
  // override qui change les horaires
  const ov = [{ date: "2026-09-10", serviceNumber: 1, startTime: "18:30", endTime: "20:00", maxCovers: 30, isActive: true, autoGenerated: false }];
  const s = servicesForDate("2026-09-10", templates, ov);
  ok(s[0].startTime === "18:30" && s[0].maxCovers === 30 && s[0].hasOverride, "override horaires prioritaire");
}

// --- serviceForTime ---
{
  const s = servicesForDate("2026-09-10", templates, [
    { date: "2026-09-10", serviceNumber: 2, startTime: "20:30", endTime: "22:30", isActive: true, autoGenerated: false },
  ]);
  ok(serviceForTime(s, "19:15")?.serviceNumber === 1, "19:15 → 1er service");
  ok(serviceForTime(s, "20:30")?.serviceNumber === 2, "20:30 → 2e service (fin exclusive du 1er)");
  ok(serviceForTime(s, "23:00") === null, "23:00 → aucun service");
  ok(serviceForTime(s, "12:00") === null, "12:00 → aucun service");
}

// --- servicesOverlap ---
ok(servicesOverlap([{ startMin: 1140, endMin: 1230 }, { startMin: 1200, endMin: 1350 }]) === true, "chevauchement détecté");
ok(servicesOverlap([{ startMin: 1140, endMin: 1230 }, { startMin: 1230, endMin: 1350 }]) === false, "adjacents = pas de chevauchement");

// --- planAutoExtension ---
const settings = { earliestServiceTime: "18:00", latestServiceTime: "22:30", slotGranularityMinutes: 15 };
{
  const active = servicesForDate("2026-09-10", templates, []); // seul 1er service 19:00-20:30
  let r = planAutoExtension(active, "18:15", settings);
  ok(r.ok && r.service.startTime === "18:15" && toMin(r.service.endTime) <= toMin("19:00"), "18:15 → service auto 18:15→≤19:00");

  r = planAutoExtension(active, "17:30", settings);
  ok(!r.ok && r.reason === "hors-plage", "17:30 < earliest → refus hors-plage");

  r = planAutoExtension(active, "19:30", settings);
  ok(!r.ok && r.reason === "deja-couvert", "19:30 déjà dans le 1er service → refus");

  r = planAutoExtension(active, "22:00", settings);
  ok(!r.ok, "22:00 : de 20:30 à 22:30 il reste 120 min mais start arrondi… vérifie juste refus/ok cohérent");
}
{
  // 1er service jusqu'à 20:30, latest 22:30 → une résa à 21:00 tient (21:00→22:30)
  const active = servicesForDate("2026-09-10", templates, []);
  const r = planAutoExtension(active, "21:00", settings);
  ok(r.ok && r.service.startTime === "21:00" && r.service.endTime === "22:30", "21:00 après le 1er service → 21:00→22:30");
  ok(r.service.serviceNumber >= 90, "service auto numéroté ≥ 90");
}
{
  // fenêtre trop courte : latest 20:45, résa à 20:30 juste après le 1er service
  const r = planAutoExtension(servicesForDate("2026-09-10", templates, []), "20:30", { ...settings, latestServiceTime: "20:45" });
  ok(!r.ok && r.reason === "creneau-trop-court", "fenêtre < 45 min → refus creneau-trop-court");
}

console.log(`\nservices: ${passed} passed, ${failed} failed`);
process.exit(failed ? 1 : 0);
