// Résolution des services de réservation d'une journée + extension
// automatique. Pur, sans I/O.
//
// Modèle (cahier des charges §7) :
//  - service_templates : services habituels (1er, 2e, 3e…), avec horaires
//    par défaut, capacité max de couverts, et un drapeau active_by_default.
//  - service_overrides : ajustements pour une DATE précise (activer /
//    désactiver / changer les horaires), ou service ajouté automatiquement
//    (auto_generated) quand une réservation tombe hors des services actifs.
//  - reservation_settings : bornes de la journée (earliest / latest), marge
//    de sécurité, granularité des créneaux.

export function toMin(t) {
  if (t == null) return null;
  const [h, m] = String(t).split(":");
  return Number(h) * 60 + Number(m || 0);
}
export function toHHMM(min) {
  const m = ((Math.round(min) % 1440) + 1440) % 1440;
  return `${String(Math.floor(m / 60)).padStart(2, "0")}:${String(m % 60).padStart(2, "0")}`;
}

// Jour de semaine d'une date "YYYY-MM-DD" : 0 = dimanche … 6 = samedi.
// Midi local → pas d'effet de fuseau sur la bascule de jour.
export function weekdayOf(dateStr) {
  return new Date(`${dateStr}T12:00:00`).getDay();
}

function num(v, fallback) {
  const n = Number(v);
  return Number.isFinite(n) ? n : fallback;
}

// Services ACTIFS pour une date donnée, triés par heure de début.
// `templates` : lignes service_templates. `overrides` : lignes service_overrides
// (toutes dates — filtrées ici sur `dateStr`).
// Ordre de résolution, par service :
//   0. service_overrides exact pour (dateStr, n) → décide tout (priorité absolue).
//   1. sinon → activation par jour de semaine (tpl.activeWeekdays, repli
//      tpl.activeByDefault).
export function servicesForDate(dateStr, templates = [], overrides = []) {
  const ovByNum = new Map();
  for (const o of overrides) {
    if (o.date === dateStr) ovByNum.set(o.serviceNumber, o);
  }
  const wd = weekdayOf(dateStr);
  const numbers = new Set([...templates.map((t) => t.serviceNumber), ...ovByNum.keys()]);
  const out = [];
  for (const n of numbers) {
    const tpl = templates.find((t) => t.serviceNumber === n) || null;
    const ov = ovByNum.get(n) || null;
    let active, startTime, endTime, maxCovers, autoGenerated, label;
    if (ov) {
      active = ov.isActive;
      startTime = ov.startTime;
      endTime = ov.endTime;
      maxCovers = ov.maxCovers ?? tpl?.maxCovers ?? null;
      autoGenerated = ov.autoGenerated;
      label = tpl?.label || `Service ${n}`;
    } else {
      active = Array.isArray(tpl?.activeWeekdays)
        ? tpl.activeWeekdays.includes(wd)
        : !!tpl?.activeByDefault;
      startTime = tpl?.startTime;
      endTime = tpl?.endTime;
      maxCovers = tpl?.maxCovers ?? null;
      autoGenerated = false;
      label = tpl?.label || `Service ${n}`;
    }
    if (!active || startTime == null || endTime == null) continue;
    out.push({
      serviceNumber: n,
      label,
      startTime,
      endTime,
      startMin: toMin(startTime),
      endMin: toMin(endTime),
      maxCovers,
      autoGenerated,
      hasOverride: !!ov,
    });
  }
  return out.sort((a, b) => a.startMin - b.startMin);
}

// Service (résolu) dans lequel tombe une heure "HH:MM", ou null. Fin exclusive.
export function serviceForTime(services, time) {
  const m = toMin(time);
  return services.find((s) => m >= s.startMin && m < s.endMin) || null;
}

export function servicesOverlap(services) {
  const s = [...services].sort((a, b) => a.startMin - b.startMin);
  for (let i = 1; i < s.length; i++) {
    if (s[i].startMin < s[i - 1].endMin) return true;
  }
  return false;
}

// Durée par défaut d'un service auto : moyenne des services existants, sinon
// 120 min.
function defaultDurationMin(services) {
  const durs = services.map((s) => s.endMin - s.startMin).filter((d) => d > 0);
  if (!durs.length) return 120;
  return Math.round(durs.reduce((a, b) => a + b, 0) / durs.length);
}

// Propose un service auto pour accueillir une réservation à `time` qui ne
// tombe dans aucun service actif. NE décale PAS les services existants : il
// remplit le trou disponible dans la plage [earliest, latest] sans chevauchement.
// Renvoie { ok:true, service:{serviceNumber,startTime,endTime,maxCovers} } ou
// { ok:false, reason }.
export function planAutoExtension(activeServices, time, settings = {}) {
  const reqRaw = toMin(time);
  if (reqRaw == null) return { ok: false, reason: "heure-invalide" };
  const earliest = toMin(settings.earliestServiceTime ?? settings.earliest_service_time ?? "12:00");
  const latest = toMin(settings.latestServiceTime ?? settings.latest_service_time ?? "22:30");
  const gran = num(settings.slotGranularityMinutes ?? settings.slot_granularity_minutes, 15);
  const minService = 45;

  if (reqRaw < earliest || reqRaw >= latest) return { ok: false, reason: "hors-plage" };
  if (serviceForTime(activeServices, time)) return { ok: false, reason: "deja-couvert" };

  const start = Math.max(earliest, Math.floor(reqRaw / gran) * gran);
  const sorted = [...activeServices].sort((a, b) => a.startMin - b.startMin);
  // borne haute : début du prochain service qui commence après `start`, sinon `latest`
  const next = sorted.find((s) => s.startMin >= start);
  // borne basse : fin du service précédent (au cas où `start` chevauche sa fin)
  const prev = [...sorted].reverse().find((s) => s.endMin <= reqRaw + 1);
  const lowBound = prev ? Math.max(start, prev.endMin) : start;
  const highBound = Math.min(latest, next ? next.startMin : latest);

  if (highBound - lowBound < minService) return { ok: false, reason: "creneau-trop-court" };

  const dur = defaultDurationMin(activeServices);
  const end = Math.min(highBound, lowBound + dur);

  const usedNumbers = new Set(activeServices.map((s) => s.serviceNumber));
  let serviceNumber = 90;
  while (usedNumbers.has(serviceNumber)) serviceNumber++;

  return {
    ok: true,
    service: {
      serviceNumber,
      startTime: toHHMM(lowBound),
      endTime: toHHMM(end),
      maxCovers: activeServices.length ? Math.round(activeServices.reduce((a, s) => a + (s.maxCovers || 0), 0) / activeServices.length) || null : null,
    },
  };
}
