// Résolution des services de réservation d'une journée + extension
// automatique. Pur, sans I/O.
//
// Modèle (cahier des charges §7) :
//  - service_templates : services habituels (1er, 2e, 3e…), avec horaires
//    par défaut, capacité max de couverts, et un drapeau active_by_default.
//  - service_overrides : ajustements pour une DATE précise (activer /
//    désactiver / changer les horaires), ou service ajouté automatiquement
//    (auto_generated) quand une réservation tombe hors des services actifs.
//  - reservation_settings : bornes de la journée (earliest / latest), marge
//    de sécurité, granularité des créneaux.

export function toMin(t) {
  if (t == null) return null;
  const [h, m] = String(t).split(":");
  return Number(h) * 60 + Number(m || 0);
}
export function toHHMM(min) {
  const m = ((Math.round(min) % 1440) + 1440) % 1440;
  return `${String(Math.floor(m / 60)).padStart(2, "0")}:${String(m % 60).padStart(2, "0")}`;
}

// Jour de semaine d'une date "YYYY-MM-DD" : 0 = dimanche … 6 = samedi.
// Midi local → pas d'effet de fuseau sur la bascule de jour.
export function weekdayOf(dateStr) {
  return new Date(`${dateStr}T12:00:00`).getDay();
}

// Lundi (format "YYYY-MM-DD") de la semaine calendaire française (lundi →
// dimanche) contenant cette date.
export function mondayOf(dateStr) {
  const d = new Date(`${dateStr}T12:00:00`);
  const wd = d.getDay(); // 0 = dimanche … 6 = samedi
  const diffToMonday = wd === 0 ? -6 : 1 - wd;
  d.setDate(d.getDate() + diffToMonday);
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
}

function num(v, fallback) {
  const n = Number(v);
  return Number.isFinite(n) ? n : fallback;
}

// Nombre de jours couverts par une exception (pour départager : plus la plage
// est courte, plus l'exception est spécifique donc prioritaire).
function exceptionSpanDays(e) {
  return (new Date(e.dateEnd) - new Date(e.dateStart)) / 86400000;
}

// Services ACTIFS pour une date donnée, triés par heure de début.
// `templates` : lignes service_templates. `overrides` : lignes service_overrides
// (toutes dates — filtrées ici sur `dateStr`). `exceptions` : lignes
// service_exceptions (plages de fermeture / ré-ouverture).
// Ordre de résolution, par service :
//   0. service_overrides exact pour (dateStr, n) → décide tout (priorité absolue).
//   1. service_exceptions couvrant la date :
//      - exception PAR SERVICE (serviceNumber === n) la plus étroite → 'off'
//        force inactif, 'on' force actif (même horaires template).
//      - sinon exception GLOBALE (serviceNumber null) la plus étroite : 'off'
//        gagnant → journée fermée ; 'on' ou aucune → on retombe sur la semaine.
//   2. sinon → activation par jour de semaine (tpl.activeWeekdays, repli
//      tpl.activeByDefault).
export function servicesForDate(dateStr, templates = [], overrides = [], exceptions = []) {
  const ovByNum = new Map();
  for (const o of overrides) {
    if (o.date === dateStr) ovByNum.set(o.serviceNumber, o);
  }
  const wd = weekdayOf(dateStr);

  // Exceptions couvrant cette date (comparaison de chaînes YYYY-MM-DD, OK).
  const dayExc = (exceptions || []).filter((e) => e.dateStart <= dateStr && dateStr <= e.dateEnd);
  const globals = dayExc
    .filter((e) => e.serviceNumber == null)
    .sort((a, b) => exceptionSpanDays(a) - exceptionSpanDays(b) || (a.mode === "on" ? -1 : 1) - (b.mode === "on" ? -1 : 1));
  const globalClosed = globals[0]?.mode === "off";
  const perServiceExc = (n) =>
    dayExc
      .filter((e) => e.serviceNumber === n)
      .sort((a, b) => exceptionSpanDays(a) - exceptionSpanDays(b) || (a.mode === "off" ? -1 : 1) - (b.mode === "off" ? -1 : 1))[0] || null;

  const numbers = new Set([...templates.map((t) => t.serviceNumber), ...ovByNum.keys()]);
  const out = [];
  for (const n of numbers) {
    const tpl = templates.find((t) => t.serviceNumber === n) || null;
    const ov = ovByNum.get(n) || null;
    let active, startTime, endTime, maxCovers, maxCoversByLayout, autoGenerated, label;
    const hasEntries = (o) => o && Object.keys(o).length > 0;
    if (ov) {
      active = ov.isActive;
      startTime = ov.startTime;
      endTime = ov.endTime;
      maxCovers = ov.maxCovers ?? tpl?.maxCovers ?? null;
      maxCoversByLayout = hasEntries(ov.maxCoversByLayout) ? ov.maxCoversByLayout : tpl?.maxCoversByLayout || {};
      autoGenerated = ov.autoGenerated;
      label = tpl?.label || `Service ${n}`;
    } else {
      const ex = perServiceExc(n);
      if (ex) {
        active = ex.mode === "on";
      } else if (globalClosed) {
        active = false;
      } else {
        active = Array.isArray(tpl?.activeWeekdays)
          ? tpl.activeWeekdays.includes(wd)
          : !!tpl?.activeByDefault;
      }
      startTime = tpl?.startTime;
      endTime = tpl?.endTime;
      maxCovers = tpl?.maxCovers ?? null;
      maxCoversByLayout = tpl?.maxCoversByLayout || {};
      autoGenerated = false;
      label = tpl?.label || `Service ${n}`;
    }
    if (!active || startTime == null || endTime == null) continue;
    out.push({
      serviceNumber: n,
      label,
      startTime,
      endTime,
      startMin: toMin(startTime),
      endMin: toMin(endTime),
      maxCovers,
      maxCoversByLayout,
      autoGenerated,
      hasOverride: !!ov,
    });
  }
  return out.sort((a, b) => a.startMin - b.startMin);
}

// Capacité physique de chaque zone : somme des places max (capacityMax) des
// tables actives, non bloquées et RÉELLEMENT PLACÉES sur le plan (une table
// hors plan est hors capacité, cf. brief §7) — recalculée à chaque appel, donc
// toujours à jour dès qu'une table est ajoutée/retirée/reconfigurée. Renvoie
// { [layoutId]: covers }, une entrée par zone même à 0.
export function autoZoneCovers(tables, layouts) {
  const byLayout = {};
  for (const l of layouts || []) byLayout[l.id] = 0;
  for (const t of tables || []) {
    if (t.active === false || t.blocked) continue;
    if (t.gridRow == null || t.gridCol == null) continue;
    if (!t.layoutId || !(t.layoutId in byLayout)) continue;
    byLayout[t.layoutId] += Number(t.capacityMax) > 0 ? Number(t.capacityMax) : 0;
  }
  return byLayout;
}

// Complète les couverts max non définis (`maxCovers`/`maxCoversByLayout[id]`
// à `null`, ou zone absente du découpage — « auto ») d'une liste de services
// RÉSOLUS (sortie de servicesForDate) avec la capacité physique réelle des
// tables. Un service (ou une zone dans un service) où l'équipe a saisi un
// nombre garde sa valeur — seule l'absence de saisie est remplacée. À une
// seule zone (ou aucune), `maxCoversByLayout` reste secondaire, la capacité
// vient de `maxCovers` (auto = capacité totale de l'unique zone). À
// plusieurs zones, `maxCovers` redevient la somme des zones (comme déjà
// documenté côté écriture : "max_covers = somme").
export function applyAutoZoneCovers(services, tables, layouts) {
  const autoByLayout = autoZoneCovers(tables, layouts);
  const autoTotal = Object.values(autoByLayout).reduce((a, b) => a + b, 0);
  const multiZone = (layouts || []).length > 1;
  return (services || []).map((s) => {
    if (multiZone) {
      const maxCoversByLayout = {};
      for (const l of layouts) {
        const manual = s.maxCoversByLayout?.[l.id];
        maxCoversByLayout[l.id] = manual != null ? Number(manual) : autoByLayout[l.id] || 0;
      }
      const maxCovers = Object.values(maxCoversByLayout).reduce((a, b) => a + b, 0);
      return { ...s, maxCovers, maxCoversByLayout };
    }
    const maxCovers = s.maxCovers != null ? s.maxCovers : autoTotal;
    return { ...s, maxCovers, maxCoversByLayout: s.maxCoversByLayout || {} };
  });
}

// Service (résolu) dans lequel tombe une heure "HH:MM", ou null. Fin exclusive.
export function serviceForTime(services, time) {
  const m = toMin(time);
  return services.find((s) => m >= s.startMin && m < s.endMin) || null;
}

export function servicesOverlap(services) {
  const s = [...services].sort((a, b) => a.startMin - b.startMin);
  for (let i = 1; i < s.length; i++) {
    if (s[i].startMin < s[i - 1].endMin) return true;
  }
  return false;
}

// Classe un service résolu en "midi" (commence avant la coupure) ou "soir"
// (à partir de la coupure) — sert à restreindre un produit du menu à un
// service (fiche produit, Direction > Menu > restriction de service).
// `cutoffMin` : minutes depuis minuit (ex. PANUZZO_CUTOFF_HOUR * 60, la
// même coupure que la formule du midi).
export function serviceGroupOf(service, cutoffMin) {
  return service.startMin < cutoffMin ? "midi" : "soir";
}

// Groupes ("midi"/"soir") dont au moins un service est OUVERT maintenant
// (nowMin dans sa fenêtre [startMin, endMin)) parmi les services résolus du
// jour. Un jour où le service midi est désactivé (fermeture, exception…) n'a
// simplement aucun service dans ce groupe ce jour-là → "midi" n'apparaît
// jamais dans le résultat, quelle que soit l'heure.
export function activeServiceGroups(services, nowMin, cutoffMin) {
  const out = new Set();
  for (const s of services || []) {
    if (nowMin >= s.startMin && nowMin < s.endMin) out.add(serviceGroupOf(s, cutoffMin));
  }
  return out;
}

// Durée par défaut d'un service auto : moyenne des services existants, sinon
// 120 min.
function defaultDurationMin(services) {
  const durs = services.map((s) => s.endMin - s.startMin).filter((d) => d > 0);
  if (!durs.length) return 120;
  return Math.round(durs.reduce((a, b) => a + b, 0) / durs.length);
}

// Propose un service auto pour accueillir une réservation à `time` qui ne
// tombe dans aucun service actif. NE décale PAS les services existants : il
// remplit le trou disponible dans la plage [earliest, latest] sans chevauchement.
// Renvoie { ok:true, service:{serviceNumber,startTime,endTime,maxCovers} } ou
// { ok:false, reason }.
export function planAutoExtension(activeServices, time, settings = {}) {
  const reqRaw = toMin(time);
  if (reqRaw == null) return { ok: false, reason: "heure-invalide" };
  const earliest = toMin(settings.earliestServiceTime ?? settings.earliest_service_time ?? "12:00");
  const latest = toMin(settings.latestServiceTime ?? settings.latest_service_time ?? "22:30");
  const gran = num(settings.slotGranularityMinutes ?? settings.slot_granularity_minutes, 15);
  const minService = 45;

  if (reqRaw < earliest || reqRaw >= latest) return { ok: false, reason: "hors-plage" };
  if (serviceForTime(activeServices, time)) return { ok: false, reason: "deja-couvert" };

  const start = Math.max(earliest, Math.floor(reqRaw / gran) * gran);
  const sorted = [...activeServices].sort((a, b) => a.startMin - b.startMin);
  // borne haute : début du prochain service qui commence après `start`, sinon `latest`
  const next = sorted.find((s) => s.startMin >= start);
  // borne basse : fin du service précédent (au cas où `start` chevauche sa fin)
  const prev = [...sorted].reverse().find((s) => s.endMin <= reqRaw + 1);
  const lowBound = prev ? Math.max(start, prev.endMin) : start;
  const highBound = Math.min(latest, next ? next.startMin : latest);

  if (highBound - lowBound < minService) return { ok: false, reason: "creneau-trop-court" };

  const dur = defaultDurationMin(activeServices);
  const end = Math.min(highBound, lowBound + dur);

  const usedNumbers = new Set(activeServices.map((s) => s.serviceNumber));
  let serviceNumber = 90;
  while (usedNumbers.has(serviceNumber)) serviceNumber++;

  return {
    ok: true,
    service: {
      serviceNumber,
      startTime: toHHMM(lowBound),
      endTime: toHHMM(end),
      maxCovers: activeServices.length ? Math.round(activeServices.reduce((a, s) => a + (s.maxCovers || 0), 0) / activeServices.length) || null : null,
    },
  };
}
